const IMAGES = {
  '01d': new URL('../assets/01d.png', import.meta.url).href,
  '01n': new URL('../assets/01n.png', import.meta.url).href,
  '02d': new URL('../assets/02d.png', import.meta.url).href,
  '02n': new URL('../assets/02n.png', import.meta.url).href,
  '03d': new URL('../assets/03d.png', import.meta.url).href,
  '03n': new URL('../assets/03n.png', import.meta.url).href,
  '04d': new URL('../assets/04d.png', import.meta.url).href,
  '04n': new URL('../assets/04n.png', import.meta.url).href,
  '09d': new URL('../assets/09d.png', import.meta.url).href,
  '09n': new URL('../assets/09n.png', import.meta.url).href,
  '10d': new URL('../assets/10d.png', import.meta.url).href,
  '10n': new URL('../assets/10n.png', import.meta.url).href,
  '11d': new URL('../assets/11d.png', import.meta.url).href,
  '11n': new URL('../assets/11n.png', import.meta.url).href,
  '13d': new URL('../assets/13d.png', import.meta.url).href,
  '13n': new URL('../assets/13n.png', import.meta.url).href,
  '50d': new URL('../assets/50d.png', import.meta.url).href,
  '50n': new URL('../assets/50n.png', import.meta.url).href,
  humidity: new URL('../assets/humidity.png', import.meta.url).href,
  rain: new URL('../assets/rain.png', import.meta.url).href,
  wind: new URL('../assets/wind.png', import.meta.url).href,
  bg: new URL('../assets/bg-full.jpg', import.meta.url).href,
};

export default IMAGES;
